### ISSUE TITLE
Incorrect logging method used in cia402_data.hpp

### ISSUE THREAD

**Issue by jclinton830** [ros-industrial/ros2_canopen#207] opened 2023-10-17 03:55 UTC
During the startup of the bus for CIA402 devices the `cia402_data.hpp` in this [line](https://github.com/ros-industrial/ros2_canopen/blob/e0b5706810b699629f7222ed3c37a8ea5e6ee3cb/canopen_ros2_control/include/canopen_ros2_control/cia402_data.hpp#L66) prints out the device and its node ID on the terminal. Currently, it uses the `RCLCPP_ERROR` method instead of `RCLCPP_INFO`

**To Reproduce**
Run robot_control_setup.launch.py to reproduce

**Logs**

**Setup:**
 - Device: Dell Laptop
 - OS: Ubuntu 22.04 
 - ROS-Distro: Humble
 - Branch/Commit: humble

**Comment by ipa-cmh** [comment] 2023-10-18 04:18
Duplicate of #179. Happy to take PRs.

**Closed by ipa-cmh** 2023-10-18 04:18 UTC
Labels: bug
